export const initial = [
  {
    code: 100,
    libelle: 'Salaire de base',
    assujetiCNSS: true,
    assujetiImpot: true,
    entreBrut: true,
    entreNet: false,
    gainRetenue: 'Gain',
    type: 'Fixe',
    montant: 1000,
  },
  {
    code: 154,
    libelle: 'IU/TS',
    assujetiCNSS: false,
    assujetiImpot: false,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Fixe',
    montant: 1000,
  },
  {
    code: 201,
    libelle: 'CNSS',
    assujetiCNSS: false,
    assujetiImpot: false,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Fixe',
    montant: 1000,
  },
  {
    code: 633,
    libelle: 'Avance sur salaire',
    assujetiCNSS: false,
    assujetiImpot: false,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Variable',
    montant: 1000,
  },
  {
    code: 220,
    libelle: 'FNR',
    assujetiCNSS: false,
    assujetiImpot: true,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Variable',
    montant: 1000,
  },
  {
    code: 102,
    libelle: 'Prime anciennété',
    assujetiCNSS: true,
    assujetiImpot: true,
    entreBrut: true,
    entreNet: false,
    gainRetenue: 'Gain',
    type: 'Fixe',
    montant: 1000,
  },
  {
    code: 110,
    libelle: 'Congé payé',
    assujetiCNSS: true,
    assujetiImpot: true,
    entreBrut: true,
    entreNet: false,
    gainRetenue: 'Gain',
    type: 'Variable',
    montant: 1000,
  },
  {
    code: 111,
    libelle: 'Congé de maternité',
    assujetiCNSS: true,
    assujetiImpot: true,
    entreBrut: true,
    entreNet: false,
    gainRetenue: 'Gain',
    type: 'Variable',
    montant: 1000,
  },
  {
    code: 155,
    libelle: 'IU/TS congé payé',
    assujetiCNSS: false,
    assujetiImpot: false,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Variable',
    montant: 1000,
  },
  {
    code: 156,
    libelle: 'IU/TS congé de maternité',
    assujetiCNSS: false,
    assujetiImpot: false,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Variable',
    montant: 1000,
  },
  {
    code: 202,
    libelle: 'CNSS congé payé',
    assujetiCNSS: false,
    assujetiImpot: false,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Variable',
    montant: 1000,
  },
  {
    code: 203,
    libelle: 'CNSS congé de marternité',
    assujetiCNSS: false,
    assujetiImpot: false,
    entreBrut: false,
    entreNet: true,
    gainRetenue: 'Retenue',
    type: 'Variable',
    montant: 1000,
  },
];
